### ISSUE TITLE
Support for `sklearn.svm.OneClassSVM`

### ISSUE THREAD

**Issue by jrwalk** [jpmml/jpmml-sklearn#11]
would be awesome to add the `sklearn.svm.OneClassSVM` outlier detection system to the other LibSVM-based supported models!

**Comment by vruusmann** [comment]
The `OneClassSVM` model type is encoded as an ordinary regression-type `SupportVectorMachineModel` PMML element.

The name of the target field is fixed as `distance` (corresponds to the distance between the data record and the separating hyperplace). There's an additional boolean output field `outlier`, which binarizes the distance value using a threshold value of `0`.

```
<SupportVectorMachineModel>
  <MiningSchema>
    <MiningField name="distance" usageType="target"/>
  </MiningSchema>
  <Output>
    <OutputField name="outlier" dataType="boolean" optype="categorical">
      <Apply function="lessOrEqual">
        <FieldRef field="distance"/>
        <Constant>0</Constant>
      </Apply>
    </OutputField>
  </Output>
</SupportVectorMachineModel>
```

**Comment by jrwalk** [comment]
awesome work as always, thanks!
