### ISSUE TITLE
how to choose the version of pmml generated by sklearn2pmml

### ISSUE THREAD

**Issue by gaoyanxia** [jpmml/jpmml-sklearn#113]
the version of pmml generated by sklearn2pmml is 4.3,but 4.1 is needed,how to convert pmml4.3 to pmml4.2, thanks

**Comment by vruusmann** [comment]
The PMML version cannot be customized. The SkLearn2PMML package aims to follow the latest widely adopted PMML version (currently 4.3, but considering upgrading to 4.4 in a couple of months time).

> how to convert pmml4.3 to pmml4.2

Change the XML namespace declaration manually and see what happens. If a more sophisticated "conversion" is needed, then I'd recommend you to write your own tool for that.
