### ISSUE TITLE
Why  Estimator and Mapper

### ISSUE THREAD

**Issue by biwa7636** [jpmml/jpmml-sklearn#12]
Hi Villu, I am reading through your tutorial and wondering is there any specific reason that you want to use DataframeMapper? Using the DataframeMapper, you ended up with two pickles objects, I am planning to export the PMML to openscoring, will openscoring be compatible of deploying both the mapper and estimator into a same model? 
BTW, really great work!

**Comment by vruusmann** [comment]
In `sklearn2pmml()`, the `estimator` argument is required but the `mapper` argument is optional.

You could choose a pair of pickle files (see inside the `src/test/resources/pkl` directory), and compare the resulting PMML files first when the mapper is set and second when it is not set. For example, using `DecisionTreeAudit.pkl` and `Audit.pkl` files:
```
# Export with mapper information
java -jar target/converter-executable-1.0-SNAPSHOT.jar --pkl-estimator-input src/test/resources/pkl/DecisionTreeAudit.pkl --pkl-mapper-input src/test/resources/pkl/Audit.pkl --pmml-output Audit-with_mapper.pmml

# Export without mapper information
java -jar target/converter-executable-1.0-SNAPSHOT.jar --pkl-estimator-input src/test/resources/pkl/DecisionTreeAudit.pkl --pmml-output Audit-without_mapper.pmml

# Diff
diff Audit-with_mapper.pmml Audit-without_mapper.pmml > mapper.diff
```

Essentially, the `DataFrameMapper` object is used to construct a maximally detailed description of each feature in the feature schema:
* Names.
* Data- (eg. `string`, `integer`, `double`) and operational types (eg. `categorical`, `continuous`).
* Description of valid (eg. the category levels of a categorical field, min and max values for a continuous field), invalid and missing value spaces.
* Associated pre-processing transformations.

Let's see how the first two features of the `Audit` dataset are encoded in the data dictionary.

With mapper information:
```
<DataDictionary>
  <DataField name="Age" optype="continuous" dataType="float">
    <Interval closure="closedClosed" leftMargin="17.0" rightMargin="83.0"/>
  </DataField>
  <DataField name="Employment" optype="categorical" dataType="string">
    <Value value="Consultant"/>
    <Value value="PSFederal"/>
    <Value value="PSLocal"/>
    <Value value="PSState"/>
    <Value value="Private"/>
    <Value value="SelfEmp"/>
    <Value value="Volunteer"/>
  </DataField>
</DataDictionary>
```

The same, without mapper information:
```
<DataDictionary>
  <DataField name="x1" optype="continuous" dataType="float"/>
  <DataField name="x2" optype="continuous" dataType="float"/>
  <DataField name="x3" optype="continuous" dataType="float"/>
  <DataField name="x4" optype="continuous" dataType="float"/>
  <DataField name="x5" optype="continuous" dataType="float"/>
  <DataField name="x6" optype="continuous" dataType="float"/>
  <DataField name="x7" optype="continuous" dataType="float"/>
  <DataField name="x8" optype="continuous" dataType="float"/>
</DataDictionary>
```

The mapper information makes its way into the model data structure as well.

With mapper information:
```
<Node>
  <SimplePredicate field="Employment" operator="equal" value="Consultant"/>
</Node>
```

The same, without mapper information:
```
<Node>
  <SimplePredicate field="x2" operator="greaterThan" value="0.5"/>
</Node>
```

I would argue that it makes sense to export SkLearn models into PMML (using the [`sklearn2pmml`] (https://github.com/jpmml/sklearn2pmml) package!) whenever there is a need to analyze or interpret them.

**Comment by vruusmann** [comment]
The `DataFrameMapper` class comes from the [`sklearn-pandas`] (https://github.com/paulgb/sklearn-pandas) package, which seems like the most widely adopted way of connecting [Pandas] (http://pandas.pydata.org/) and [SkLearn] (http://scikit-learn.org/stable/).

If you prefer working with different "abstractions" in your data pre-processing workflow (such as `sklearn.pipeline.Pipeline`), then you could consider creating a dummy `DataFrameMapper` object for easy interfacing with the JPMML-SkLearn library. For more information, please see https://github.com/jpmml/jpmml-sklearn/issues/3#issuecomment-176839854
