### ISSUE TITLE
can  the TfidfVectorizer  function use analyzer='char'?

### ISSUE THREAD

**Issue by hecongqing** [jpmml/jpmml-sklearn#121]
can  the TfidfVectorizer  function use analyzer='char'?

**Comment by vruusmann** [comment]
Not sure if it can be expressed 100% in PMML markup. The `TextIndex` element (http://dmg.org/pmml/v4-3/Transformations.html#xsdElement_TextIndex) operates on words not characters. Perhaps it's possible to specify a custom RegEx-based tokenizer, which "promotes" characters to word status, but it wouldn't be very efficient/performant solution.

Perhaps the solution would be to use a Java-backed UDF instead?

I just posted a longer comment about developing Java-backed UDFs into the JPMML mailing list yesterday evening: https://groups.google.com/d/msg/jpmml/lD-s0D8uFqQ/5s3Mdmw-AwAJ

**Comment by vruusmann** [comment]
Closing as "won't fix" in order to avoid giving out false hope.
