### ISSUE TITLE
Support numerical classes in classifiers

### ISSUE THREAD

**Issue by jonbender** [jpmml/jpmml-sklearn#13]
It seems when we convert an sklearn model to PMML, the target field is assumed to be a string (even if we had defined numerical classes in sklearn):
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/Classifier.java#L51

This makes it challenging to build ensemble models that combine the outputs of multiple different PMML models, for example, and taking the average/min/median/max/etc.

Is there any way to ensure these numerical classes are preserved in conversion from sklearn to PMML with the APIs today?

**Comment by vruusmann** [comment]
JPMML-SkLearn does not provide a mechanism for defining the data type of the target field. It is assumed that it's always `string` for classifiers, and `double` for regressors.

Could you construct a sample Python script that demonstrates your use case? Most importantly, what kind of SkLearn class are you using for avg/median aggregation? Perhaps this SkLearn class has some attribute (eg. `dtype`) that reveals the correct data type.

**Comment by jonbender** [comment]
Thanks for the prompt response!  Here's a contrived example of a decision tree with numerical classes.

```python
import pandas as pd
import numpy as np
from sklearn import tree

pd.options.mode.chained_assignment = None 

def forced_tree():
    t1 = np.concatenate((np.zeros(30),np.zeros(30)+1), axis=0)
    t2 = np.concatenate((np.zeros(20)+2, np.zeros(20)+3, np.zeros(20)+4), axis=0)
    t3 = np.concatenate((np.zeros(10)+5, np.zeros(10)+6, np.zeros(10)+7, np.zeros(10)+8, np.zeros(10)+9, np.zeros(10)+10), axis=0)
    t4 = np.concatenate((np.zeros(12)+11, np.zeros(12)+12, np.zeros(12)+13, np.zeros(12)+14, np.zeros(12)+15), axis=0)
    t5 = np.concatenate((np.zeros(12)+16, np.zeros(12)+17, np.zeros(12)+18, np.zeros(12)+20, np.zeros(12)+25), axis=0)
    n_taken = np.concatenate((t1, t2, t3, t4, t5), axis=0)
    df = pd.DataFrame()
    df['n_taken'] = n_taken
    df['group'] = ''
    df['group'][0:60] = 'tier_1'
    df['group'][60:120] = 'tier_2'
    df['group'][120:180] = 'tier_3'
    df['group'][180:240] = 'tier_4'
    df['group'][240:300] = 'tier_5'
    df.group[df.group == 'tier_1'] = 1
    df.group[df.group == 'tier_2'] = 2
    df.group[df.group == 'tier_3'] = 3
    df.group[df.group == 'tier_4'] = 4
    df.group[df.group == 'tier_5'] = 6
    clf = tree.DecisionTreeClassifier()
    X = np.asarray(df.n_taken)
    X = X[:, None]
    y = list(df.group)
    clf = clf.fit(X, y)
    return clf

decision_tree = forced_tree()

print "Classes: %r" % decision_tree.classes_
print "Class type: %r" % decision_tree.classes_[0].dtype
```
And the output:
```shell
python decision_tree.py
Classes: array([1, 2, 3, 4, 6])
Class type: dtype('int64')
```

The use case is actually combining multiple PMML models (See http://dmg.org/pmml/v4-1/MultipleModels.html).  Once I generate a PMML model, I may want to combine it with other (non sklearn based PMML) models and roll them together using PMML `Segmentation`.  There are many ways of combining models but many presume a numerical output value: http://dmg.org/pmml/v4-1/MultipleModels.html#xsdType_MULTIPLE-MODEL-METHOD

It's not a critical thing for us right now, but it may be useful to have this feature.

**Comment by vruusmann** [comment]
The important line in your example is this:
```
print "Class type: %r" % decision_tree.classes_[0].dtype
```

The method `org.jpmml.sklearn.Classifier#getClasses()` returns a list of objects. In your example, list elements are of type `java.lang.Long`. The `Classifier#createSchema(FeatureMapper)` method should take notice of it, and refine the data type of the target field appropriately.

OT, but what's the tool that you're using to build model ensembles?

**Comment by jonbender** [comment]
Thanks for clarifying.

> OT, but what's the tool that you're using to build model ensembles?

Right now its just a homegrown python module that constructs the ensemble PMML given a list of PMML, Predicate pairs.  Happy to provide more details if it's useful (probably needs some cleanup before open sourcing).

**Comment by vruusmann** [comment]
I have a similar aggregation tool under construction at https://github.com/vruusmann/jpmml-toolkit Currently, the aggregation method is hard-coded as "average/weighted average", but it would be straightforward to extract it into a command-line option.

In long term, it would be nice if such tools could be integrated directly into the `sklearn2pmml` package.

**Comment by jonbender** [comment]
> In long term, it would be nice if such tools could be integrated directly into the sklearn2pmml package.

Yeah, that would be great.  

Thanks for the quick turnaround!
