### ISSUE TITLE
GBDTLRClassifier ：Whether both the original feature and gbdt feature are included

### ISSUE THREAD

**Issue by siriJR** [jpmml/jpmml-sklearn#130]
hello，My question is：Whether the final LR model only uses the features of gbdt, and does not use the original features. As far as I know, the input features of the final LR model include the original features and gbdt features。
![image](https://user-images.githubusercontent.com/41821691/75418396-4ceb8700-596e-11ea-8c80-96068c4b6aee.png)

**Comment by vruusmann** [comment]
The top-level `MiningModel` element "imports" features from the original feature space using a collection of `MiningSchema/MiningField` elements. Open your PMML file in a text editor, and take a look what they are.

There is no such thing as a "gbdt feature". There are only gbdt node identifiers, which are an internal implementation details, and do not affect the model data interface/API in any way.
