### ISSUE TITLE
Categorical feature with numeric categories ignored during convertion into PMML pipeline

### ISSUE THREAD

**Issue by apidash** [jpmml/jpmml-sklearn#131]
Hello,
I try to automate my feature engineering part and include into pmml pipeline.
For this I create sckit-learn pipeline with ColumnTransformer.
I give the example below with 3 variables (one numeric and two categorical):
```python
numeric_features  = ['AGE_DEB']
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value=-9999999))])


categorical_features = ['PROPRIETE', 'ENTITE']
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(categories = [["2", "3", "5", "6"], ["AL", "ML", "MU"]], handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])

# Append classifier to preprocessing pipeline.
# Now we have a full prediction pipeline.
clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', RandomForestClassifier())])

# fit
clf.fit(df_model[['AGE_DEB','PROPRIETE','ENTITE']], df_model["INDICATEUR_FRAUDE_H6"])
```
And then I convert my pipeline to PMML one:

```python
import sklearn2pmml 
pmml_pipe = sklearn2pmml.make_pmml_pipeline(clf, ['AGE_DEB', 'PROPRIETE', 'ENTITE'], "INDICATEUR_FRAUDE_H6")
sklearn2pmml.sklearn2pmml(pmml_pipe, "testPIPsklearn.pmml", with_repr=True)
```

The problem is that my variable PROPRIETE which is categorical but with the numbers as categories is IGNORED by make_pmml_pipeline only if I choose to keep the specific categories by using `categories = ["2", "3", "5", "6"]` . The result is here:

![image](https://user-images.githubusercontent.com/15040266/77435702-eaf23600-6de2-11ea-9490-d73cbc600429.png)

**Comment by apidash** [comment]
For information, it works when I add some letters for each element, for ex:
`categories = ["2", "3", "5", "6"]` becomes `categories = ["2a", "3a", "5a", "6a"]`.
But it doesn't a solution for me.


![image](https://user-images.githubusercontent.com/15040266/77441958-5986c200-6dea-11ea-970d-0f586ad90d9e.png)

**Comment by vruusmann** [comment]
> The problem is that my variable PROPRIETE which is categorical but with the numbers as categories is IGNORED.

If a variable does not appear in the resulting PMML document, then it means that this variable is not needed by the model (SkLearn2PMML automatically removes all redundant variables).

Check for yourself - if you ask Scikit-Learn to compute variable importances for "PROPRIETE", then it will be 0 (ie. zero importance).

If you transform "PROPRIETE" from integer to string, then Scikit-Learn treats it differently during model training, and this variable becomes significant.

Check for yourself - the importance for "PROPRIETE" should be non-zero in this case, and the predictive function inside the model is also different - you are getting different predictions!

The conversion to PMML representation simply makes it obvious that Scikit-Learn treats the "PROPRIETE" variable differently depending on its data type (integer vs string). The SkLearn2PMML package simply Scikit-Learn model object, it does not transform or modify it any way.

> .. if I choose to keep the specific categories ..

You can manually "decorate" each variable with its operational type and much more.

Simply insert a `sklearn2pmml.decoration.CategoricalDomain` as the first step into your pipeline:
```python
categorical_transformer = Pipeline(steps=[
    ('domain', CategoricalDomain(dtype = int)), # THIS!
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder())])
```

There is a technical article about extending Scikit-Learn with feature specifications available here: https://openscoring.io/blog/2020/02/23/sklearn_feature_specification_pmml/

**Comment by vruusmann** [comment]
@apidash I believe the following line is wrong in your code - if the "PROPRIETE" variable is integer, then you should specify category values as a list of integers (not as a list of strings):

Now:
```python
OneHotEncoder(categories = [["2", "3", "5", "6"], ["AL", "ML", "MU"]], handle_unknown='ignore')
```

Should be:
```python
OneHotEncoder(categories = [[2, 3, 5, 6], ["AL", "ML", "MU"]], handle_unknown='ignore'))
```

**Comment by apidash** [comment]
@vruusmann thank you for your clair explanations. Your last suggestion works well for me.
Simply, I was convinced that if I forced my variable to be string by usisng `.astype('object')`, I should treat it like string by selecting the categories like this `"2", "3", ...`, but not.
