### ISSUE TITLE
can mapper be just the StandardScaler

### ISSUE THREAD

**Issue by vijaymahadevan** [jpmml/jpmml-sklearn#14]
Can I used the StandardScaler from sklearn.preprocessing as the mapper I export as a pkl file instead of exporting the sklearn_pandas.DataFrameMapper?

**Comment by vijaymahadevan** [comment]
If that is not supported, how would i do preprocessing on the data without using the DataFrameMapper

**Comment by vruusmann** [comment]
The `mapper` argument must be of type `sklearn_pandas.DataFrameMapper`.

What's the problem with employing it?
```
mapper = DataFrameMapper([
	(columns[: -1], StandardScaler()), # Independent variables
	(columns[-1], None) # The dependent variable
])
```
