### ISSUE TITLE
How to Change OutputField Name for TPOT's StackingEstimator

### ISSUE THREAD

**Issue by nuttracy** [jpmml/jpmml-sklearn#141]
Hi Villu,

I am creating a two-stage pipeline using StackingEstimator. The first stage is two estimators, and the second stage is meta estimator using the output of stage1 - two estimators. 
What I've found is that sklearn2pmml automatically assigns the OutputField name with the number of features in each StackingEstimator. So, if I pass the same features (ex: 24) to base_estimator1 and base_estimator2. I receive the following error in sklearn2pmml:

SEVERE: Failed to convert
java.lang.IllegalArgumentException: Field stack(24) is already defined
	at org.jpmml.converter.PMMLEncoder.checkName(PMMLEncoder.java:279)
       ....

We can bypass the error by adding ColumnTransformer in front of each estimator and pass different number of features to each estimator. However, we do want the two estimators use same features. Do you know if there is a way we can manually change the naming conversion of OutputField name for each StackingEstimator?

Thank you so much!

Here is my pipeline:

```
response_col = 0
base_estimator1 = RandomForestRegressor(random_state=1234,max_depth=3)
base_estimator1.fit(X,df_it[dep_var])
yX1 = StackingEstimator(base_estimator1).transform(X)

keep_score1 = ColumnTransformer([("keep", "passthrough", [response_col])], remainder = "drop")
y1 = keep_score1.fit_transform(yX1)

base_estimator2 = RandomForestRegressor(random_state=1234,max_depth=3)
base_estimator2.fit(X,df_it[dep_var])
yX2 = StackingEstimator(base_estimator2).transform(X)

keep_score2 = ColumnTransformer([("keep", "passthrough", [response_col])], remainder = "drop")
y2 = keep_score2.fit_transform(yX2)

meta_estimator = LinearRegression()
meta_estimator.coef_ = np.array([1.0, -0.5]).T
meta_estimator.intercept_ = 0.0

stacking = FeatureUnion([ 
            ('base_pipeline1', Pipeline([
                ("base_estimator1", StackingEstimator(base_estimator1)),
                ('keep_score1', keep_score1) 
            ])),
            ('base_pipeline2', Pipeline([
                ("base_estimator2", StackingEstimator(base_estimator2)),
                ('keep_score2', keep_score2) 
            ]))  
                                 ], verbose = True)

pmml_pipeline = \
PMMLPipeline([
    ('stacking',stacking),
    ('meta_estimator', meta_estimator)
])

y_oot_pred_t = pmml_pipeline.predict(X)

sklearn2pmml(pmml_pipeline, 'test-Iris1.pmml',with_repr = True)
```

**Comment by vruusmann** [comment]
This question is about TPOT's stacking estimator (`tpot.builtins.stacking_estimator.StackingEstimator`), not Scikit-Learn's stacking estimators `sklearn.ensemble._stacking.StackingClassifier` or `sklearn.ensemble._stacking.StackingRegressor`?

The short answer - the "formula" for generating `OutputField` element names is hard-coded, there is no API/way to change it programmatically (not in Java, much less in Python):
https://github.com/jpmml/jpmml-sklearn/blob/1.6.2/src/main/java/tpot/builtins/StackingEstimator.java#L93

The current formula assumes a linear workflow where there is a one `StackingEstimator` (as the final estimator of a pipeline). You have a split workflow, where the same feature matrix is sent to two different `StackingEstimator` instances.

This formula doesn't have to be like this. It could include a model identifier or smth like that for disambiguation purposes.

**Comment by nuttracy** [comment]
> This question is about TPOT's stacking estimator (`tpot.builtins.stacking_estimator.StackingEstimator`), not Scikit-Learn's stacking estimators `sklearn.ensemble._stacking.StackingClassifier` or `sklearn.ensemble._stacking.StackingRegressor`?
> 
> The short answer - the "formula" for generating `OutputField` element names is hard-coded, there is no API/way to change it programmatically (not in Java, much less in Python):
> https://github.com/jpmml/jpmml-sklearn/blob/1.6.2/src/main/java/tpot/builtins/StackingEstimator.java#L93
> 
> The current formula assumes a linear workflow where there is a one `StackingEstimator` (as the final estimator of a pipeline). You have a split workflow, where the same feature matrix is sent to two different `StackingEstimator` instances.
> 
> This formula doesn't have to be like this. It could include a model identifier or smth like that for disambiguation purposes.

Yes. It's for TPOT's stacking estimator. Do you think I should also address this issue in TPOT's forum?

**Comment by vruusmann** [comment]
> Do you think I should also address this issue in TPOT's forum?

Not necessary - this issue is 100% local to SkLearn2PMML/JPMML-SkLearn.

**Comment by vruusmann** [comment]
> there is no API/way to change it programmatically (not in Java, much less in Python)

To elaborate, "there is no API/way for an **end user** to change it programmatically".

You have access to JPMML-SkLearn source code, you may change this line (eg. to `FieldName.create("stack(" + features.size() + ", " + System.identityHashCode(this) + ")");`), recompile and be happy!

**Comment by nuttracy** [comment]
> > there is no API/way to change it programmatically (not in Java, much less in Python)
> 
> To elaborate, "there is no API/way for an **end user** to change it programmatically".
> 
> You have access to JPMML-SkLearn source code, you may change this line (eg. to `FieldName.create("stack(" + features.size() + ", " + System.identityHashCode(this) + ")");`), recompile and be happy!

Very helpful. Thank you!

**Comment by vruusmann** [comment]
Starting from SkLearn2PMML version 0.60.0 (based on JPMML-SkLearn version 1.6.3), it's possible to override the default derived field name using the `pmml_name_` attribute.

In the above example, the following code change would cause the two TPOT stacking estimators called `first_branch` and `second_branch`:

```python
stacking_base_estimator1 = StackingEstimator(base_estimator1)
stacking_base_estimator2 = StackingEstimator(base_estimator2)

# THIS!
stacking_base_estimator1.pmml_name_ = "first_branch"
stacking_base_estimator2.pmml_name_ = "second_branch"

stacking = FeatureUnion([ 
	('base_pipeline1', Pipeline([
		("base_estimator1", stacking_base_estimator1),
		('keep_score1', keep_score1) 
	])),
	('base_pipeline2', Pipeline([
		("base_estimator2", stacking_base_estimator2),
		('keep_score2', keep_score2) 
	]))
])
```
