### ISSUE TITLE
Using a result plused by two numbers as a new feature when generating PMML file?

### ISSUE THREAD

**Issue by HelloLadsAndGents** [jpmml/jpmml-sklearn#149]
from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import StandardScaler
from sklearn2pmml.decoration import ContinuousDomain

column_preprocessor = DataFrameMapper([
    (["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"], [ContinuousDomain(), StandardScaler()])
])

for example
How can i use  "Sepal.Length" add "Sepal.Width", or "Sepal.Width" plus  "Petal.Width"  as a new feature  and then predict?

i konw that self-defined func is kind of complex , is there any other ways or some usable function for this kind of situation?

thanks

**Comment by vruusmann** [comment]
> How can i use "Sepal.Length" add "Sepal.Width", or "Sepal.Width" plus "Petal.Width" as a new feature and then predict?

Use the `sklearn2pmml.preprocessing.ExpressionTransformer` transformation type:

```python
column_preprocessor = DataFrameMapper([
    (["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"], [ContinuousDomain(), StandardScaler()]),
    (["Sepal.Length", "Sepal.Width"], [ExpressionTransformer("X[0] + X[1]"), StandardScaler()])
])
```

If summing is all you need, then you can also use the `sklearn2pmml.preprocessing.Aggregator` transformation type:
```python
column_preprocessor = DataFrameMapper([
    (["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"], [ContinuousDomain(), StandardScaler()]),
    (["Petal.Length", "Petal.Width"], [Aggregator(function = "sum"), StandardScaler()])
])
```

**Comment by HelloLadsAndGents** [comment]
thanks a lot ^_^
