### ISSUE TITLE
Deploy JAR RandomForestRegressor on Android Studio

### ISSUE THREAD

**Issue by ys31jp** [jpmml/jpmml-sklearn#169]
Hi, Im new to this. I have my custom model on RandomForestRegressor and converted into pmml. I wan to deploy this model on Android Studio. If I convert into JAR file will I be able to use it on Android Studio. 

Perhaps this is simple questions. But I'm totally new. Please understand me. Thanks

**Comment by vruusmann** [comment]
Closing as functional duplicate of https://github.com/jpmml/jpmml-evaluator/issues/244
