### ISSUE TITLE
scikit-learn v1.3.X support

### ISSUE THREAD

**Issue by Oj5000** [jpmml/jpmml-sklearn#188]
Current version only supports scikit-learn v1.2.2

**Comment by vruusmann** [comment]
> Current version only supports scikit-learn v1.2.2

I know.

The version check was added fairly recently, in SkLearn2PMML version 0.96.0:
https://github.com/jpmml/jpmml-sklearn/commit/20de2caf441c5e4fa9b360c5730ee22a7ff6a265

Therefore, as a workaround, you may install some older SkLearn2PMML package version, which does not perform the version check.
