### ISSUE TITLE
Output pmml version

### ISSUE THREAD

**Issue by fazlan-nazeem** [jpmml/jpmml-sklearn#21]
How can we specify the pmml version when generating the output?

**Comment by vruusmann** [comment]
You can't. The fact that JPMML-SkLearn is generating PMML 4.3 is a feature, not a bug - the resulting PMML documents are more compact and expressive.

You might want to see the related discussion in JPMML mailing list:
https://groups.google.com/d/msg/jpmml/2tsIQoc1iEA/ZFXgmrtlBAAJ
