### ISSUE TITLE
numpy function is log1p not ln1p

### ISSUE THREAD

**Issue by infiton** [jpmml/jpmml-sklearn#26]
currently the FunctionTransformer (https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/preprocessing/FunctionTransformer.java#L120) is looking for a numpy `ufunc` `ln1p` but the numpy function is actually `log1p` (https://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations)

**Comment by infiton** [comment]
@vruusmann, thanks!

**Comment by vruusmann** [comment]
@infiton In a couple of hours time, there will be public releases of JPMML-SkLearn 1.2.6 and sklearn2pmml 0.17.0 that will incorporate this fix.
