### ISSUE TITLE
Need help to understand the generated PMML for neural network  

### ISSUE THREAD

**Issue by palaiyacw** [jpmml/jpmml-sklearn#29]
I am using the following code of scikit-learn to generate the pmml file. I need help to understand how it is generating the final result. 

[pipeline.txt](https://github.com/jpmml/jpmml-sklearn/files/760480/pipeline.txt)

```
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5), random_state=1, max_iter=100)

clf.fit(X_train, y_train)
pipeline = PMMLPipeline([
  ('clf', clf)
])

sklearn2pmml(pipeline, "pipeline.pmml",debug = True)
```

**1)** I don't understand the significance of `Neuron id=logistic/1`. I mentioned only one hidden layer with 5 neurons. Why it has been generated in the final PMML. Moreover, My final output is supposed to be one neuron why is it showing two having neuron id to be `event/true` and `event/false` 

```
<NeuralLayer activationFunction="logistic">
			<Neuron id="logistic/1" bias="0.0">
				<Con from="2/1" weight="1.0"/>
			</Neuron>
		</NeuralLayer>
		<NeuralLayer activationFunction="identity">
			<Neuron id="event/false" bias="1.0">
				<Con from="logistic/1" weight="-1.0"/>
			</Neuron>
			<Neuron id="event/true" bias="0.0">
				<Con from="logistic/1" weight="1.0"/>
			</Neuron>
		</NeuralLayer>
		<NeuralOutputs>
			<NeuralOutput outputNeuron="event/false">
				<DerivedField optype="categorical" dataType="string">
					<NormDiscrete field="y" value="0"/>
				</DerivedField>
			</NeuralOutput>
			<NeuralOutput outputNeuron="event/true">
				<DerivedField optype="categorical" dataType="string">
					<NormDiscrete field="y" value="1"/>
				</DerivedField>
			</NeuralOutput>
		</NeuralOutputs>
```

**2)** Also, I am using the following code to predict the score. I couldn't understand what is the difference between `evaluator.getOutputFields()` and `evaluator.getTargetFields()` . Moreover, ` boolean target = (boolean)(targetFieldValue instanceof Boolean);` casting this  in `Double` gives the error. Ideally, my neural network should give the probability in double where as it is giving boolean values. Please help 

```
			PMML pmml = readPMML(new File("pipeline.pmml"));        	
			ModelEvaluatorFactory modelEvaluatorFactory = ModelEvaluatorFactory.newInstance();
			ModelEvaluator<?> modelEvaluator = modelEvaluatorFactory.newModelEvaluator(pmml);
        	Evaluator evaluator = (Evaluator)modelEvaluator;
        	
        	List<InputField> inputFields = evaluator.getInputFields();
        	Map<FieldName, FieldValue> arguments = new LinkedHashMap<FieldName,FieldValue>();
			
			Double[] inputArray = new Double[]{0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9};

			for (int i = 0; i < inputFields.size(); i++) {
				FieldName inputFieldName = inputFields.get(i).getName();			 
			 	FieldValue inputFieldValue = inputFields.get(i).prepare(inputArray[i]);
			 	arguments.put(inputFieldName, inputFieldValue);
			}
			Map<FieldName, ?> results = evaluator.evaluate(arguments);
			Set keys = results.keySet();

   			for (Iterator i = keys.iterator(); i.hasNext(); ) {
				FieldName targetFieldName = (FieldName)i.next();
    			System.out.println("The field name is " + targetFieldName.getValue());      
   			}

			List<TargetField> targetFields = evaluator.getTargetFields();
			System.out.println(targetFields.size());
			for (int i =0 ; i < targetFields.size(); i++){
				FieldName targetFieldName = targetFields.get(i).getName();
    			System.out.println("The field name is " + targetFieldName.getValue());
    			Object targetFieldValue = results.get(targetFieldName);
    			boolean target = (boolean)(targetFieldValue instanceof Boolean);
    			System.out.println("the output is" + target);
			}

			List<OutputField> outputFields = evaluator.getOutputFields();	
			System.out.println(outputFields.size());			
			for(int i =0 ; i < outputFields.size(); i++ ){
			    FieldName outputFieldName = outputFields.get(i).getName();
				System.out.println("The field name is " + outputFieldName.getValue());

			    Object outputFieldValue = results.get(outputFieldName);
				boolean output = (boolean)(outputFieldValue instanceof Boolean);
				System.out.println("output value is " + output);
			}

```

**Comment by vruusmann** [comment]
The `Neuron@id` attribute is a free-form identifier. The JPMML-SkLearn library aims to generate meaningful/self-explanatory identifiers in order to make the human interpretation easier.

Please see the [NeuralNetwork](http://dmg.org/pmml/v4-3/NeuralNetwork.html) chapter in the PMML specification for the meaning of `NeuralInput`, `Neuron` and `NeuralOutput` elements.

**Comment by palaiyacw** [comment]
I read [NeuralNetwork](http://dmg.org/pmml/v4-3/NeuralNetwork.html) chapter from this link. But still i couldn't understand why it generated one extra `NeuralLayer`. Moreover, could you please help me with the second issue. I am new to this and not able to figure out.

**Comment by vruusmann** [comment]
@palaiyacw I think that you should work on your attitude.

**Comment by palaiyacw** [comment]
@vruusmann I am really sorry I expected a better answer from you rather than just pasting the link. Hence, I downvoted your answer. Moreover, reading that link doesn't answer my question. I was not asking  to explain the terminologies used in the PMML rather I asked why it behaved in a certain fashion (generating one extra NeuralLayer) .
