### ISSUE TITLE
Conversion of `sklearn.pipeline.Pipeline` objects

### ISSUE THREAD

**Issue by ricaldam** [jpmml/jpmml-sklearn#3]
As you explain in the tutorial,  jpmml-scikitlearn can be used to convert into pmml format two kinds of objects (both stored in in .pkl): mappers and estimators. Mappers come from DataFrameMappers created with sklearn-pandas, and estimators come from models created via scikit-learn. 
In my case I would like to convert to pmml an object Pipeline created directly via scikit-learn. Of course I can rewrite my python code in terms of DataFrameMappers, but it would be more convenient for me if I could convert directly the object Pipeline. Thank you.

**Comment by vruusmann** [comment]
There is a conceptual difference between SkLearn (and other Numpy-based Python machine learning frameworks) and PMML regarding the representation of individual data records. For SkLearn, a data record is a row in a data matrix. It is assumed that the "layout" of the data matrix is fixed during the lifecycle of the application (eg. the number and ordering of columns in all *testing* data matrices will be identical to that of the *training* data matrix). For PMML, a data record is a collection of key-value tuples.

Therefore, the conversion from SkLearn to PMML must address the change of mindset from "vector representation" (ie. values are identified by the position in the list) to "map representation" (ie. values are identified by name). Class `sklearn_pandas.DataFrameMapper` is perfectly suited for this job.

**Comment by vruusmann** [comment]
A `sklearn.pipeline.Pipeline` object has typically much more responsibilities (eg. search of hyperparameter space, cross-validation etc.) than a `sklearn_pandas.DataFrameMapper` object. This extra functionality is needed for model training, but not for model deployment. Therefore, if you wanted to keep your application design "clean", then you would take the original training `Pipeline` object and extract its vital pieces to a new, leaner and meaner deployment `Pipeline` object. However, if you wanted to make your workflow really transparent and robust, then I would suggest extracting into the `DataFrameMapper` representation instead.

The conversion from `Pipeline` to `DataFrameMapper` should be easy to do in Python. The list of fully initialized transformers is already present in the `Pipeline` object. The only piece of information that needs to be provided externally is the list of column names. The usage might look something like this:
```
Pipeline irisPipeline = ..
DataFrameMapper irisMapper = pipeline_to_dfmapper(irisPipeline, ["Sepal_Width", "Sepal_Length", "Petal_Width", "Petal_Length"])
```

The function `pipeline_to_dfmapper` should reside in the `sklearn2pmml` project so that it would be easily accessible where it is needed.

**Comment by ricaldam** [comment]
Thanks for the insights. I like your approach based on the distinction between model training and model deployment (it seems the latter has been traditionally overlooked in many ML libraries). As you suggest, it should be easy to adapt my workflow to make it cleaner and more robust.

**Comment by ricaldam** [comment]
I've been trying to use `sklearn_pandas.DataFrameMapper` as you suggested, but I'm getting an error related with the manipulation of sparse matrices.
```
transformer = sklearn.feature_extraction.text.TfidfVectorizer()
mapper = DataFrameMapper([
        ('ce', transformer),
        ('category', None)
    ])
transformed_train_data = mapper.fit_transform(train_data)
```
yields the following error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-119-22274276b15e> in <module>()
----> 1 transformed_train_data = mapper.fit_transform(train_data)

/usr/local/lib/python2.7/dist-packages/sklearn/base.pyc in fit_transform(self, X, y, **fit_params)
    453         if y is None:
    454             # fit method of arity 1 (unsupervised transformation)
--> 455             return self.fit(X, **fit_params).transform(X)
    456         else:
    457             # fit method of arity 2 (supervised transformation)

/usr/local/lib/python2.7/dist-packages/sklearn_pandas/dataframe_mapper.pyc in transform(self, X)
    122         # Otherwise, combine as normal arrays.
    123         if any(sparse.issparse(fea) for fea in extracted):
--> 124             stacked = sparse.hstack(extracted).tocsr()
    125             # return a sparse matrix only if the mapper was initialized
    126             # with sparse=True

/usr/local/lib/python2.7/dist-packages/scipy/sparse/construct.pyc in hstack(blocks, format, dtype)
    454 
    455     """
--> 456     return bmat([blocks], format=format, dtype=dtype)
    457 
    458 

/usr/local/lib/python2.7/dist-packages/scipy/sparse/construct.pyc in bmat(blocks, format, dtype)
    587     nnz = sum([block.nnz for block in blocks[block_mask]])
    588     if dtype is None:
--> 589         dtype = upcast(*tuple([blk.dtype for blk in blocks[block_mask]]))
    590 
    591     row_offsets = np.concatenate(([0], np.cumsum(brow_lengths)))

/usr/local/lib/python2.7/dist-packages/scipy/sparse/sputils.pyc in upcast(*args)
     60             return t
     61 
---> 62     raise TypeError('no supported conversion for types: %r' % (args,))
     63 
     64 

TypeError: no supported conversion for types: (dtype('float64'), dtype('O'))
```
It seems to be related to the issue reported here https://github.com/paulgb/sklearn-pandas/issues/51

I understand this is completely independent from `sklearn2pmml`, but since it impacts its usage, maybe you can give me a workaround.

**Comment by vruusmann** [comment]
As a workaround, you should `fit` all your transformer objects with the training data before constructing the `DataFrameMapper` object:
```
transformer = ...
transformer.fit(X)

mapper = DataFrameMapper([
  ('x', transformer),
  ('y', None)
])
```

The `DataFrameMapper` object is just a description about how the data preparation was done. It does not have to be used for actual work.

**Comment by vruusmann** [comment]
I just noticed that your example script uses the `sklearn.feature_extraction.text.TfidfVectorizer` transformation type.

This transformation is not supported by the JPMML-SkLearn project at the moment. If you really need it, then you should open another issue about it.

**Comment by ricaldam** [comment]
Thank you for the workaround. It worked indeed. 
Unfortunately, I do really need `sklearn.feature_extraction.text.TfidfVectorizer`. I'll open another issue then
