### ISSUE TITLE
Support for custom transformers

### ISSUE THREAD

**Issue by doodnayr** [jpmml/jpmml-sklearn#30]
I'm trying to use a custom transformer, for example, this simple one takes the max value across columns:

```
class MaxTransform(BaseEstimator, TransformerMixin):
    def fit(self, x, y=None):
        return self
    def transform(self, x):
        return x.max(1) # or np.max(x, 1)

mapper = DataFrameMapper([
    (["x1","x2"], [MaxTransform()])
])

model=ensemble.GradientBoostingClassifier()

pipeline = PMMLPipeline([
    ("mapper", mapper),
    ("estimator", model)
])
```

However, when I try to build the pmml, I'm getting :
"The value object (Python class __main__.MaxTransform) is not a Transformer or is not a supported Transformer subclass"

Am I doing something wrong or is this not currently supported? I'm able to fit the pipeline, but not convert it to pmml.

**Comment by doodnayr** [comment]
I've also attempted using [FunctionTransformer](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html) with no luck.

**Comment by vruusmann** [comment]
Related to https://github.com/jpmml/sklearn2pmml/issues/20

**Comment by doodnayr** [comment]
Embarrassing I missed that. Thanks.

**Comment by vruusmann** [comment]
You need to create a Java counterpart for your Python transformer class, and register it with the JPMML-SkLearn runtime.

The Java counterpart for your `main.MaxTransform` would look like this:
```Java
public class MaxTransform extends Transformer {

  public MaxTransform(String module, String name){
    super(module, name);
  }

  @Override
  public List<Feature> transform(List<String> ids, List<Feature> features, SkLearnEncoder encoder){
    Apply apply = PMMLUtil.createApply("max");
    for(Feature feature : features){
      apply.addExpression(feature.ref());
    }
    ids.clear();
    FieldName name = FieldName.create("max(x1, x2)"); // XXX
    ids.add(name.getValue());
    DerivedField derivedField = encoder.createDerivedField(name, DataType.DOUBLE, OpType.CONTINUOUS, apply);
    return Collections.<Feature>singletonList(new ContinuousFeature(derivedField));
  }
}
```

Then, create a JAR file that contains this Java class, and an appropriate `META-INF/sklearn2pmml.properties` file. And let the `sklearn2pmml(..)` function know about this JAR file by specifying the `user_classpath` argument.

So, it's not very difficult if you know exactly what needs to be done.

**Comment by vruusmann** [comment]
I'm reopening this issue, because it points out a need to improve documentation in this area. Most probably, it will materialize in the form of a JPMML-SkLearn-Plugin demo project, and an accompanying Slideshare presentation. Unfortunately, can't make any promises time-wise.

If you feel like giving this plugin project a try, then feel free to ask related technical questions in this thread.

**Comment by vruusmann** [comment]
Here's a template project with step-by-step instructions: https://github.com/jpmml/sklearn2pmml-plugin
