### ISSUE TITLE
Runt time exception while converting a random forest classifier model trained for bag of words using sklearn TfidfVectorizer

### ISSUE THREAD

**Issue by Purvihana** [jpmml/jpmml-sklearn#33]
Unable to obtain pmml while converting a random forest trained for a TfidfVectorizer bag of words and the below exception is thrown RuntimeError: The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams

**Comment by vruusmann** [comment]
> The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams

So, what was printed to standard output and/or error streams?
