### ISSUE TITLE
Supporting `sklearn.feature_extraction.text.TfidfVectorizer`

### ISSUE THREAD

**Issue by ricaldam** [jpmml/jpmml-sklearn#4]
It would be great if the transformation `sklearn.feature_extraction.text.TfidfVectorizer` can be supported by JPMML-sklearn. It would be even better if both `sklearn.feature_extraction.text.CountVectorizer` and  `sklearn.feature_extraction.text.TfidfTransformer` can be supported (`TfidfVectorizer` is the combination of these two)

**Comment by vruusmann** [comment]
This is a major change, because it requires updating the core JPMML-Evaluator library also. The difficult part is class `CountVectorizer`, because it must be translated to PMML's [TextIndex element] (http://dmg.org/pmml/v4-2-1/Transformations.html#xsdElement_TextIndex) and evaluated as such.

Earlier this week, I did take a deeper look into `CountVectorizer` and `TfidfVectorizer` transformers. My estimation was that it would take approximately two weeks to implement a full solution (a MVP-style solution would be doable in a week or so).

**Comment by vruusmann** [comment]
Can you provide an example script that would capture the intended use of `TfidfVectorizer`? This class takes very many parameters, so it would be important to know which subset of parameters should be implemented first.

There's example usage in SkLearn documentation, but I'm interested in finding out the exact details of your use case. For demonstration purposes, you could replace your real text corpus with some demo text corpus (publicly accessible in the internet) though.

**Comment by ricaldam** [comment]
Well, I work almost exclusively with text datasets, so this functionality would be really helpful. And I'm pretty sure this is something other people would appreciate. If I can help you one way or another, just let me know.
Thank you very much

**Comment by ricaldam** [comment]
I'm currently working almost exclusively with text datasets, so this functionality would indeed be really helpful. And I'm pretty sure this is something other people would appreciate.

Regarding the script, I think you can consider the example given in the sklearn documentation http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction, since in my case I'm just using the default parameters of `TfidfVectorizer`. That might change in the future, but for the moment you can consider this is my use case.

Thank you very much

**Comment by ricaldam** [comment]
Hello @vruusmann. Is there any news regarding this issue? Thank you.

**Comment by clocklear** [comment]
I too am interested if there is any progress on this front.

**Comment by vruusmann** [comment]
Fixed in commit 36916c34bd2f931c979c607d42e6a75bdfed422e
