### ISSUE TITLE
Add possibility to add information to the pmml header.

### ISSUE THREAD

**Issue by mackaiver** [jpmml/jpmml-sklearn#5]
Hello!

Great little tool.  I would like the possibility to add stuff to the header of the pmml file as specified in the [pmml standard](http://dmg.org/pmml/v4-2-1/Header.html#xsdElement_Header). 

For exampe one could add text to the <Description/> tag of the header. I find this useful for storing  information about how the model was trained.  I dont know whats the best way to do this. I guess it could be done via commandline arguments? 

The project we are working on will rely heavily on [sklearn2pmml](https://github.com/jpmml/sklearn2pmml). 
I guess adding something like `sklearn2pmml(model, mapper, path, dict_with_header_information)` is feasable?

Thanks!

**Comment by vruusmann** [comment]
The PMML specification defines the [`MiningBuildTask` element] (http://dmg.org/pmml/v4-2-1/GeneralStructure.html#xsdElement_MiningBuildTask) exactly for this purpose.

The description of the estimator object can be generated automatically inside the `sklearn2pmml()` function by calling `repr(estimator)`.

For example, `repr(RandomForestIris)` would print the following:
```
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=13, verbose=0, warm_start=False)
```

**Comment by vruusmann** [comment]
Would the automatically generated `MiningBuildTask` element address your use case? Or do you need something more flexible, where you can insert arbitrary text to the header (probably in the form of [`Annotation` elements] (http://dmg.org/pmml/v4-2-1/Header.html))?

This "enhancement" of PMML documents does not need to happen during the `sklearn2pmml()` function call. You could also develop your own command-line application that can perform arbitrary edits during some sort of post-processing stage.

**Comment by mackaiver** [comment]
> Would the automatically generated MiningBuildTask element address your use case?

That would already help alot. There are a couple of other things we write into our model.  

> This "enhancement" of PMML documents does not need to happen during the sklearn2pmml() function call. You could also develop your own command-line application that can perform arbitrary edits during some sort of post-processing stage.

You're right and thats what we are doing currently. However we tend to produce large models (in the order of gigabytes(uncompressed) ) which introduces seom overhead when "enhancing" the pmml in a seperate step. 
But I can see that this might be a very specific task which is outside the scope of jpmml.  :smile:

**Comment by vruusmann** [comment]
Function `sklearn2pmml` now has a boolean parameter `with_repr`. If set to `True`, then the string representation of both estimator and mapper objects is stored in the `PMML/MiningBuildTask` element.
