### ISSUE TITLE
How to use KMeans?

### ISSUE THREAD

**Issue by Ngthoai** [jpmml/jpmml-sklearn#72]
I don't know using KMeans? Can you give me a example?
Example in Python:
clt = KMeans(n_clusters=n, n_jobs=1, n_init=n_init)
clt.fit(img.reshape(-1, 3))

How change to Java?
Can you help me?

**Comment by vruusmann** [comment]
> I don't know using KMeans? Can you give me a example?

It doesn't matter what feature transformations or estimator types (classification, regression, clustering) you are using. Simply wrap all workflow steps into `sklearn2pmml.PMMLPipeline` container:
```Python
from sklearn2pmml import PMMLPipeline

pipeline = PMMLPipeline([
  ("clusterer", KMeans(n_clusters = n))
])
pipeline.fit(img.reshape(-1, 3))

from sklearn2pmml import sklearn2pmml

sklearn2pmml(pipeline, "pipeline.pmml")
```
