### ISSUE TITLE
Feature Request: Regular Expression Transformers

### ISSUE THREAD

**Issue by tyers** [jpmml/jpmml-sklearn#81]
Hi Villu,
I'm looking for a way to apply the two PCRE functions available within the PMML specification within a PMML pipeline / dataframe mapper.
I've not seen anything in the docs here that suggests this is currently possible outside of implementing a custom transformer through the sklearn2pmml-plugin framework, so happy to be corrected on this.
Many thanks
Chris

Ref docs.
http://dmg.org/pmml/v4-3/BuiltinFunctions.html#replace
http://dmg.org/pmml/v4-3/BuiltinFunctions.html#matches

**Comment by vruusmann** [comment]
> I've not seen anything in the docs here that suggests this is currently possible outside of implementing a custom transformer through the sklearn2pmml-plugin framework.

You're correct on both points.

It shouldn't be anything too difficult. By analogy with the `sklearn2pmml.preprocessing.StringNormalizer` transfrormation, it would take approximately 20 to 30 lines of Python and Java code to have it all ready:
https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/preprocessing/__init__.py#L161-L183
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn2pmml/preprocessing/StringNormalizer.java

**Comment by vruusmann** [comment]
Could you share your python code? Specifically, I would like to see what external libraries/functions did you choose to implement PCRE-compatible string transformations.

**Comment by tyers** [comment]
here is the python code i have - minimal import requirements, but i'm not 100% confident i've ended up with full PCRE compatibility.

```
from sklearn2pmml.util import eval_rows
from sklearn.base import TransformerMixin
from pandas import Series

class ReMatchTransformer(TransformerMixin):

  def __init__(self, pattern = None, case_sensitive = False):
    if pattern is  None:
      raise ValueError("Pattern is None")
    self.pattern = pattern
    self.case_sensitive = case_sensitive

  def fit(self, raw_X, y = None):
    return self

  def transform(self, raw_X, y = None):
    X = Series(raw_X)
    return X.str.contains(self.pattern,case=self.case_sensitive)

class ReReplaceTransformer(TransformerMixin):

  def __init__(self, pattern = None, replace = None, case_sensitive = False):
    if pattern is  None:
      raise ValueError("Pattern is None")
    if replace is  None:
      raise ValueError("Replace is None")
    self.pattern = pattern
    self.replace = replace
    self.case_sensitive = case_sensitive

  def fit(self, raw_X):
    return self

  def transform(self, raw_X):
    X = Series(raw_X)
    return X.str.replace(self.pattern,self.replace,case=self.case_sensitive,regex=True)


class ReContainsTransformer(TransformerMixin):
  def __init__(self, case_sensitive = False):
    self.case_sensitive = case_sensitive

  def fit(self, x):
    return self

  def transform(self, x):
    func = lambda m: bool(Series(m[0]).str.contains(m[1],case=self.case_sensitive).values)
    y = eval_rows(x, func)
    return y.reshape(-1, 1)
```

**Comment by vruusmann** [comment]
I'm not sure it's possible to use `Series.str.contains` and `Series.str.replace` methods to implement the Python side of PMML built-in functions:
1. The regex engine must obey PCRE syntax. The Pandas documentation doesn't seem to confirm it.
2. `case=self.case_sensitive`. PMML built-in functions don't provide a mechanism for toggling case sensitivity like that. Perhaps it can be made part of the PCRE pattern (eg. the `(?i)` prefix).

**Comment by tyers** [comment]
ok - thanks Villu - that is what i was worried about.
I've found the python-pcre package that looks as though it might work in this scenario, but i'm struggling to get the PCRE dependency installed on my system (windows) so i'm not able to progress at the moment unfortunately.

**Comment by vruusmann** [comment]
> I've found the python-pcre package that looks as though it might work in this scenario, but i'm struggling to get the PCRE dependency installed

One option would be to use "the best RE engine that is available":
1. Python PCRE
2. Python built-in RE

The fall-back from the first option to the second would be accompanied by an appropriate warning message ("PCRE engine not available, results might not be reproducible between Python and PMML when using more complex patterns").

**Comment by tyers** [comment]
thanks for the suggestion. I'm trying to get access to a linux based system (corp systems at work) so i can try the python-pcre package rather than coding it blind.

**Comment by tyers** [comment]
Hi Villu,
I've updated again and removed the Pandas requirement. Regular expressions now use PCRE or fallback to re. The string manipulations are now also just using base python operations. 
```python
from sklearn2pmml.util import eval_rows
from sklearn.base import TransformerMixin
import warnings

try:
    import pcre
    PCRE_AVAILABLE = True
except ImportError:
    import re
    PCRE_AVAILABLE = False


class ReMatchTransformer(TransformerMixin):

  def __init__(self, pattern = None):
    if PCRE_AVAILABLE == False:
      warnings.warn("PCRE engine not available, results might not be reproducible between Python and PMML when using more complex patterns", Warning)

    if pattern is  None:
      raise ValueError("Pattern is None")
    self.pattern = pattern

  def fit(self, x, y = None):
    return self

  def transform(self, x, y = None):
    if PCRE_AVAILABLE:
      func = lambda m: bool(pcre.search(self.pattern,m))
    else:
      func = lambda m: bool(re.search(self.pattern,m))
    y = eval_rows(x, func)
    return y


class ReReplaceTransformer(TransformerMixin):

  def __init__(self, pattern = None, replace = None):
    if PCRE_AVAILABLE == False:
      warnings.warn("PCRE engine not available, results might not be reproducible between Python and PMML when using more complex patterns", Warning)
    if pattern is  None:
      raise ValueError("Pattern is None")
    if replace is  None:
      raise ValueError("Replace is None")
    self.pattern = pattern
    self.replace = replace

  def fit(self, x):
    return self

  def transform(self, x):
    if PCRE_AVAILABLE:
      func = lambda m: pcre.sub(self.pattern,self.replace,m)
    else:
      func = lambda m: re.sub(self.pattern,self.replace,m)
    y = eval_rows(x, func)
    return y


class ReContainsTransformer(TransformerMixin):

  def fit(self, x):
    return self

  def transform(self, x):
    if PCRE_AVAILABLE:
      func = lambda m: bool(pcre.search(m[1],m[0]))
    else:
      func = lambda m: bool(re.search(m[1],m[0]))
    y = eval_rows(x, func)
    return y.reshape(-1, 1)


class ConcatTransformer(TransformerMixin):
  def __init__(self, separator = None):
    if separator == None:
      self.separator = ''
    else:
      self.separator = separator

  def fit(self, x):
    return self

  def transform(self, x):
    func = lambda X: self.separator.join(X)
    y = eval_rows(x, func)
    return y.reshape(-1, 1)


class SubStrTransformer(TransformerMixin):
  def __init__(self, start = None, length = None):
    self.start = start - 1  # convert to 0 index
    self.stop = start - 1 + length # convert from length to stop index

  def fit(self, x):
    return self

  def transform(self, x):
    func = lambda X: X[self.start:self.stop]
    y = eval_rows(x, func)
    return y.reshape(-1, 1)

```

**Comment by tyers** [comment]
Hi Villu,
Many thanks for taking the effort to get my clunky transformers integrated nicely in to all of the relevant packages. 

I've updated my pretty much all of my feature pre-processors off of my custom implementation now, but the one that i'm missing is the ContainsTransformer, which allows a second variable to effectively be used as the pattern within a MatchTransformer.

So where a MatchesTransformer would generate PMML like this (eg - checking for an email domain):
```
<Apply function="matches">
  <FieldRef field="email"/>
  <Constant>googlemail</Constant>  
</Apply>
```
a ContainsTransformer would result in PMML like this (eg - checking for the presence of a name within the email):
```
<Apply function="matches">
  <FieldRef field="email"/>
  <FieldRef field="forename"/>  
</Apply>
```
is this something you would consider extending your implementation with?

Thanks

**Comment by vruusmann** [comment]
@tyers I quite didn't figure out the difference between your `ReMatchTransformer` and `ReContainsTransformer`, but your current code example shows that it's about making the "pattern string" customizable.

I'd rather not have a a separate top-level transformer class for this - it should be possible to make the `sklearn2pmml.preprocessing.MatchesTransformer` a bit more flexible. Perhaps, if it's constructed with `pattern = None`, then it expects a two-column argument matrix, where the first column is "matchable string" and the second one is "pattern string".

**Comment by tyers** [comment]
Villu, That sounds ideal if you are not wanting to make this an entirely separate transformer class.
