### ISSUE TITLE
Reproducibility issues with TfIdfVectorizer 

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-sklearn#89]
The issue was originally raised under the JPMML-Evaluator project, but it definitely belong here:
https://github.com/jpmml/jpmml-evaluator/issues/136

**Comment by vruusmann** [comment]
Perhaps the behaviour of TfIdfVectorizer has changed between Scikit-Learn 0.19 and 0.20 versions.

**Comment by vinluvie** [comment]
I did try running it again with 0.19.0 Sklearn but i still get mismatches
Here are the versions that I ran with
```
python: 3.6.6
sklearn: 0.19.0
sklearn.externals.joblib: 0.11
pandas: 0.23.4
sklearn_pandas: 1.7.0
sklearn2pmml: 0.39.0
java: 1.8.0_171
```

**Comment by vinluvie** [comment]
i actually just tried to use 1.3.11 on the pmml-evaluator, and now the result match 100%

**Comment by vruusmann** [comment]
> i actually just tried to use 1.3.11 on the pmml-evaluator, and now the result match 100%

That cannot be! Thanks for a data point, will check/confirm when I can.

**Comment by vinluvie** [comment]
Yea, actually I tested all version, only 1.4.3 is not matching . And have been using sklearn 0.20

**Comment by vruusmann** [comment]
@vinluvie Sorry about bouncing you back and forth between two different issues.

Your diagnosis is correct - there appears to have been a code regression between the 1.4.2 and 1.4.3 versions of the JPMML-Evaluator library. Will try to pinpoint the exact location.
