### ISSUE TITLE
Support for sklearn VotingClassifier

### ISSUE THREAD

**Issue by bkellerman** [jpmml/jpmml-sklearn#9]
Any plans on adding this?   :)

**Comment by vruusmann** [comment]
Class [`VotingClasifier`] (http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingClassifier.html) can be represented in PMML without problems:
* The `hard` voting scheme maps to `(WEIGHTED_)MAJORITY_VOTE` multiple model method.
* The `soft` voting scheme maps to `(WEIGHTED_)AVERAGE` multiple model method.

It's a matter of priorities.
