### ISSUE TITLE
Add support for type cast expressions

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-sklearn#98]
Extracting a feature request from another thread - the expression transformer class should enable the use of common Python data type cast functions such as `bool(x)`, `float(x)`, `int(x)`, `str(x)`, and maybe some other: https://github.com/jpmml/sklearn2pmml/issues/134#issuecomment-466575897

Would be straightforward to implement, if the PMML specification allowed expression elements to specify a `dataType` attribute: http://mantis.dmg.org/view.php?id=169

Until PMML schema version 4.4 is released, must restort to workarounds such as helper `DerivedField` elements.

**Comment by tyers** [comment]
Hi Villu,
Just wanted to post here as i have another use case for this feature - seems you already have it on the cards anyway.
With the option to use int(x) within an expression transformer it would become possible to calculate a modulo. eg. a check for whether X[0] % 12 == 0 could be defined as "(X[0] - (12 * int(X[0] / 12))) == 0".
Chris

**Comment by vruusmann** [comment]
> With the option to use int(x) within an expression transformer it would become possible to calculate a modulo.

The upcoming PMML 4.4. schema version adds support for the `modulo` operator (http://mantis.dmg.org/view.php?id=207), so there's not much point in trying to "emulate" it with other means. 

The `modulo` operator is already implemented in the JPMML-Evaluator library:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/Functions.java#L95-L106

So, what is missing, is that the `ExpressionTranslator` component should detect Python modulo expressions, and translate them to the following:
``` xml
<Apply function="x-modulo">
  <FieldRef field="dividend"/>
  <FieldRef field="divisor"/>
</Apply>
```

**Comment by tyers** [comment]
Villu, thanks for the prompt response. If this is forthcoming in a native fashion then this is even better. Are you aware of an approx drop date for v4.4?

**Comment by vruusmann** [comment]
> Are you aware of an approx drop date for v4.4?

No idea.

But the JPMML ecosystem can implement it as `x-modulo` vendor extension to v4.3 (ie. right away), and then "soft upgrade" to `modulo` once v4.4 is announced.

**Comment by tyers** [comment]
Again, sounds ideal! thanks
